version: '2'
services:
  stats-db:
    image: mysql
    ports:
      - "4300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: stats 
      MYSQL_HOST: stats-db
  stats-ms:
    build: .
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4006 -b '0.0.0.0'"
    ports:
      - "3305:4006"
    depends_on:
      - stats-db
